### ISSUE TITLE
about inference

### ISSUE THREAD

**Issue by Fengww2014** [desa-lab/Perceptogram#1]
What information is the semantic decoder decoding?  are they generated with eeg and text embeding?

**Comment by simonfei123** [comment]
Thank you for your comment,

It is not conclusive which embedding gives the most semantic information. But if you're asking how the CLIP-Text mapping is trained: each image has a category name; the category name for each image is encoded into CLIP-Text, which is used to train a mapping from eeg to the CLIP-Text embedding.

Refer to thingseeg2_scripts/cliptext_extract_features.py and thingseeg2_scripts/cliptext_regression.py
