### ISSUE TITLE
meg reconstruction 

### ISSUE THREAD

**Issue by Cirri12** [desa-lab/Perceptogram#3]
Thank you for this work, authors!  I want to know how much time did it take for you to run the get_stims1b.py script?  Since its not running on any GPU how many CPU cores did you use?

**Comment by simonfei123** [comment]
Model name:             Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
    CPU family:           6
    Model:                62
    Thread(s) per core:   2
    Core(s) per socket:   10
    Socket(s):            2

40 cpu threads in total (not all of them are necessarily used by that script)

The process takes about 30 minutes

**Comment by Cirri12** [comment]
@simonfei123 Thanks for the reply. I am getting an error during the preprocessing while running the preprocess_meg.ipynb. It shows an index error(list index out of range) in this line:  combined_annot = np.array([item if item in ['catch', 'BAD boundary', 'EDGE boundary'] else f'{item.split("/")[0]}/{labels[index1b_list][i]}/{item.split("/")[1]}'

My things_text_labels.npy gives output in the form of a table and has labels for all image categories, but I saw in the .ipynb file,  you got it in array type. Could it be because of that I am getting an error ?
